# Generated by Django 5.0.4 on 2024-07-23 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("print_tag_app", "0002_packing"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefInvoice",
            fields=[
                ("ref_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qr_code", models.CharField(max_length=255)),
                ("invoice", models.CharField(blank=True, max_length=255, null=True)),
                ("po_no", models.CharField(blank=True, max_length=100, null=True)),
                ("cust_sup", models.CharField(blank=True, max_length=100, null=True)),
                ("part_name", models.CharField(blank=True, max_length=255, null=True)),
                ("part_no", models.CharField(blank=True, max_length=255, null=True)),
                ("lot_mat", models.CharField(blank=True, max_length=100, null=True)),
                ("lot_prod", models.CharField(blank=True, max_length=100, null=True)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("mc", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("qty", models.IntegerField(blank=True, null=True)),
                (
                    "ref_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="print_tag_app.refinvoice",
                    ),
                ),
            ],
        ),
    ]
