# Generated by Django 5.0.4 on 2024-07-23 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("print_tag_app", "0003_refinvoice_invoice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="ref_tag",
            new_name="ref_invoice",
        ),
    ]
